config/routes.rb
Rails.application.routes.draw do
  root :to => 'welcome#index'
  resources :services 
  resources :clothings

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  devise_for :admins
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RiseUpResource</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="http://fonts.googleapis.com/css?family=Dancing+Script:700|EB+Garamond" rel="stylesheet" type="text/css" />
    <link href='http://fonts.googleapis.com/css?family=Raleway:100,200,300,400' rel='stylesheet'  type='text/css'>

    <link rel="icon" type="image/x-icon" href="favibird.png">

    <script src="//maps.google.com/maps/api/js?key=AIzaSyCAEQaLEhyJDPt8edfAVaTM1kkZKZnbb50"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
  </head>

  <body>
    <nav>
      <% if user_signed_in? %>
        <p class="navbar-text pull-right">
          Logged in as <strong><%= current_user.email %></strong> |
          <%= link_to 'edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "log out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> |
          <%= link_to 'HOME', root_path, :class => 'navbar-link' %>
        </p>
      <% else %>
        <p class="navbar-text pull-right">
          <%= link_to "sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "log in", new_user_session_path, :class => 'navbar-link'  %> |
          <%= link_to 'HOME', root_path, :class => 'navbar-link' %>
        </p>
      <% end %>
    </nav>
    <br>
    <br>
    <br>
    <div class='row'>
    <div class='logo'>
      <%= image_tag('birdflight.png', id:'birdflight') %>
      <a href="/"><h1>Rise Up Resource</h1><a>
    </div>
  </div>
  <div class="nav-row">
    <nav class="resource-nav">
      <p class="navbar-next">
        <%= link_to 'EMERGENCY', root_path, :class => 'navbar-link-1' %>  
        <%= link_to 'FOOD', services_path, :class => 'navbar-link-1' %>  
        <%= link_to 'CLOTHING', clothings_path, :class => 'navbar-link-1' %>  
        <%= link_to 'COUNSELING', root_path, :class => 'navbar-link-1' %>  
        <%= link_to 'EMPLOYMENT', root_path, :class => 'navbar-link-1' %>  
        <%= link_to 'FINANCIAL ASSISTANCE', root_path, :class => 'navbar-link-1' %>  
        <%= link_to 'HEALTH', root_path, :class => 'navbar-link-1' %>  
        <%= link_to 'LEGAL', root_path, :class => 'navbar-link-1' %>  
        <%= link_to 'ADDICTION', root_path, :class => 'navbar-link-1' %>  
        <%= link_to 'YOUTH', root_path, :class => 'navbar-link-1' %>  
        <%= link_to 'GLBTQI', root_path, :class => 'navbar-link-1' %>  
        <%= link_to 'VETERANS', root_path, :class => 'navbar-link-1' %>
      </p>
    </nav>
  </div>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
    <footer> <p>Contact: <a href="mynameisdanaweiss@gmail.com">mynameisdanaweiss@gmail.com</a></p></footer>
  </body>
</html>